name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@latest

      - name: Commit & Push
        run: |
          git config --local user.email "modikanav9@gmail.com"
          git config --local user.name "Kanav-Profile"
          git add .
          git commit -m "Generate 3D graph"
          git push
